#server:
#  port: 9999
#
#spring:
#  application:
#    name: sc-gateway-service
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
