
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766



spring:
  application:
    name: config-single-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BeyondXuz/springcloud-xz #配置文件所在仓库
          username: BeyondXuz
          password: xuzong518
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录