server:
  port: 9999

spring:
  application:
    name: sc-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  rabbitmq:
    host: mq.xuzong.xyz
    port: 5672
    username: guest
    password: guest
    listener:
      concurrency: 10
      max-concurrency: 20
      prefetch: 5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
