
# 高可用注册中心，通过互相注册来实现。

server:
  port: 8761

# 服务名
spring:
  application:
    name: eureka

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
      defaultZone: http://localhost:8761/eureka/
#   eureka本身也是服务，会进行注册，false关闭注册
    register-with-eureka: true
    fetch-registry: true
  server:
#   关闭自我保护机制
    enable-self-preservation: false



#server:
#  port: 8762
#
## 服务名
#spring:
#  application:
#    name: eureka
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
#    # eureka本身也是服务，会进行注册，false关闭注册
#    register-with-eureka: false
#    fetch-registry: false
#  server:
#    # 关闭自我保护机制
#    enable-self-preservation: false



#server:
#  port: 8763
#
## 服务名
#spring:
#  application:
#    name: eureka
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#    # eureka本身也是服务，会进行注册，false关闭注册
#    register-with-eureka: false
#    fetch-registry: false
#  server:
#    # 关闭自我保护机制
#    enable-self-preservation: false